export const AI_SYSTEM_NOTICE =
  '<!-- tessl-code-review:ai-notice:v1 This review was generated by an AI system. Validate and verify its claims before taking action. -->';

/** Append the hidden AI-system notice exactly once to rendered Markdown. */
export function withAiSystemNotice(body) {
  const value = String(body ?? '');
  if (value.includes(AI_SYSTEM_NOTICE)) return value;
  let separator = '';
  if (value.length > 0) separator = value.endsWith('\n') ? '\n' : '\n\n';
  return `${value}${separator}${AI_SYSTEM_NOTICE}`;
}
